# Generated by Django 6.0.1 on 2026-01-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_quantity_remove_order_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, help_text='Optional name to identify this event', max_length=200),
        ),
    ]
